### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by johanssone** [erictossell/nixflakes#47]
May I ask what you are using to create your "structure" pictures, like https://github.com/erictossell/nixflakes/blob/main/docs/screens/FlakeStructure2.png?

Thanks!

**Comment by hugosenari** [comment]
<img src="https://github.com/erictossell/nixflakes/assets/863299/11d2f0fd-1992-4065-84e9-6ba121029299" width=40% >

As an [graphical enjoyer](https://discourse.nixos.org/t/nix-ecosystem-mind-map/28682/) I'm here to ask same question

**Comment by erictossell** [comment]
I'm using excalidraw.com: [available here](https://exclalidraw.com). 

The most recent diagrams are available [here](https://excalidraw.com/#json=sLBGevErl5v1fcsJFiCal,AiRJKK_znO87_l2usZ1f7Q) if you want something to jump off from.
