### ISSUE TITLE
diagram producing info

### ISSUE THREAD

**Issue by iharh** [erictossell/nixflakes#67]
Hello.
If it's not a secret, could you share the software/system you used for building such awesome diagrams???

**Comment by erictossell** [comment]
They're built with excalidraw! 

If you want to borrow them or use them as a jumping off point they're available here: https://excalidraw.com/#json=sLBGevErl5v1fcsJFiCal,AiRJKK_znO87_l2usZ1f7Q

**Comment by iharh** [comment]
Thank you very much!
